### ISSUE TITLE
CPP_REST_INCLUDE_DIR not found error

### ISSUE THREAD

**Issue by xgdgsc** [MatrixManAtYrService/HelloWorld-cpprestsdk#1]
Thanks for sharing this code. I' m getting an error with this on archlinux. When using: 
```
find_package(CppREST REQUIRED) # populates CPP_REST_INCLUDE_DIR and CPP_REST_LIBRARY
include_directories(SYSTEM ${CPP_REST_INCLUDE_DIR})
```
Error:
```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CPP_REST_INCLUDE_DIR
```

**Comment by xgdgsc** [comment]
Adding "/usr/include/cpprest" to `FIND_PATH` seem to work.

**Comment by xgdgsc** [comment]
On Ubuntu also need to add `/usr/lib/x86_64-linux-gnu/` to `FIND_LIBRARY`

**Comment by MatrixManAtYrService** [comment]
Glad you figured it out.

I created this repo while evaluating cpprestsdk for a project.  We decided do go with something else (https://github.com/eidheim/Simple-Web-Server) so this repo is pretty much abandoned, which is why I failed to get back to you in a timely manner.  I'll update the readme.
